name: deixa
description: A Crypto Project.
publish_to: "none"
version: 1.0.0+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.12.29
  audioplayers: null
  audioplayers_darwin: ^1.0.1
  auto_route: null
  bip32:
    git:
      url: https://github.com/ludowkm/bip32-dart.git
      ref: support-null-safety
  bip39: ^1.0.6
  bubble: ^1.2.1
  cached_network_image: ^3.1.0
  cached_video_player: ^2.0.3
  carousel_slider: ^4.0.0
  change_app_package_name: ^1.0.0
  clipboard: ^0.1.3
  cloud_firestore: ^4.0.3
  country_code_picker: ^2.0.2
  cron: ^0.4.1
  cupertino_icons: ^1.0.3
  dartz: ^0.10.1
  device_info_plus: ^3.2.2
  dio: ^4.0.6
  dotted_border: ^2.0.0+1
  easy_localization_loader: ^1.0.0
  encrypt: ^5.0.1
  eth_sig_util: ^0.0.8
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  firebase_analytics: ^10.0.3
  firebase_core: ^2.4.0
  firebase_dynamic_links: ^5.0.3
  firebase_messaging: ^14.0.3
  fl_chart: ^0.50.0
  flutter:
    sdk: flutter
  flutter_braintree: ^2.0.0+1
  flutter_dotenv: ^5.0.2
  flutter_icons_nullsafty: ^1.0.0
  flutter_inappwebview: ^5.4.3+7
  flutter_local_notifications: ^12.0.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.12
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^1.0.4
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  geolocator: ^9.0.1
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.1.10
  google_maps_place_picker_mb: ^2.0.0-mb.22
  google_sign_in: ^5.4.2
  googleapis: ^9.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  http_parser: ^4.0.1
  image_cropper: ^2.0.3
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.4
  in_app_review: ^2.0.3
  infinite_scroll_pagination: ^3.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  introduction_screen: ^3.0.0
  lazy_load_scrollview: ^1.3.0
  loading_overlay: ^0.3.0
  local_auth: ^1.1.11
  ntp: ^2.0.0
  package_info_plus: ^1.4.2
  path: ^1.8.1
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  pin_code_fields: ^7.3.0
  pinput: ^2.2.12
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.0
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
  qr_flutter: ^4.0.0
  readmore: ^2.2.0
  record_mp3:
    git:
      url: https://github.com/fluttercandies/flutter_record_mp3
  sentry_flutter: null
  share: ^2.0.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  swipe_to: ^1.0.2
  syncfusion_flutter_core: ^20.3.50
  syncfusion_flutter_sliders: ^20.2.44
  timeago: ^3.1.0
  translator: ^0.1.7
  twilio_phone_verify: ^2.0.0
  url_launcher: ^6.0.10
  uuid: ^3.0.4
  video_player: ^2.4.7
  walletconnect_qrcode_modal_dart:
    git:
      url: https://github.com/ludovn/walletconnect_qrcode_modal_dart.git
      ref: 844a4baea170e4188c68677bbf8f9226dff5cba9
  web3auth_flutter:
    git: https://github.com/Web3Auth/web3auth-flutter-sdk.git
  web3dart: ^2.3.5
  webfeed: ^0.7.0
  webview_flutter:
  decimal: ^2.3.0
  socket_io_client: ^2.0.0
  firebase_auth: ^4.2.3
  flutter_facebook_auth: ^5.0.7
  twitter_login: ^4.2.3
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  google_static_maps_controller: ^1.0.0
  web3_provider: ^1.1.3
  rational: ^2.2.2
  flutter_cupertino_datetime_picker: ^3.0.0
  date_time_picker: ^2.1.0


dev_dependencies:
  auto_route_generator: null
  build_runner: ^2.1.11

  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  injectable_generator: null
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/appicon.png"
  adaptive_icon_foreground: "assets/ic_launcher/appicon.png"
  adaptive_icon_background: "#5F2269"
  # "assets/icon/logo_bg.png"

flutter:
  # generate: true
  uses-material-design: true
  assets:
    - assets/gif/
    - assets/images/
    - assets/icon/
    - assets/svg/
    - assets/abis/
    - assets/podcast/
    - assets/abis/nft/
    - assets/map_mode.json
    - assets/translations/ar.json
    - assets/translations/de.json
    - assets/translations/en.json
    - assets/translations/es.json
    - assets/translations/fr.json
    - assets/translations/hi.json
    - assets/translations/id.json
    - assets/translations/ja.json
    - assets/translations/ko.json
    - assets/translations/nl.json
    - assets/translations/pt.json
    - assets/translations/ru.json
    - assets/translations/zh.json
    - .env.development
